#!/usr/bin/env bash

set -e

DOTFILES="$HOME/i3wm-dotfiles"
TMP="$(mktemp -d)"

trap 'rm -rf "$TMP"' EXIT

[ ! -d "$DOTFILES" ] && { echo "❌ $DOTFILES not found. Clone the repo to $HOME first."; exit 1; }

cd "$DOTFILES"

echo "📦 Installing repo packages..."
sudo dnf install -y < pkg.list

echo "⚙️ Running post-install scripts..."
for script in post-install-scripts/*; do
    [ -x "$script" ] && "$script" || echo -e "\e[33m⚠ Script failed: $script\e[0m"
done

echo "📁 Installing dotfiles..."
while read -r rel; do
    [ -z "$rel" ] && continue

    src="$DOTFILES/$rel"
    dst="$HOME/$rel"

    if [ ! -e "$src" ]; then
        echo -e "\e[31m✖ Missing in repo: $rel\e[0m"
        continue
    fi

    if [ -e "$dst" ]; then
        echo -e "\e[33m⚠ Replacing $dst\e[0m"
        rm -rf "$dst"
    fi

    mkdir -p "$(dirname "$dst")"
    cp -a "$src" "$dst"

    echo -e "\e[32m✔ Installed $rel\e[0m"
done < "$DOTFILES/dotfile-paths"

echo -e "\n\n📦 Installing YoUNiX utils...\n"

curl -sS https://starship.rs/install.sh | sh
curl -fsSL https://raw.githubusercontent.com/apapamarkou/appimage-integrator/main/install | bash
curl -sSL https://raw.githubusercontent.com/apapamarkou/lazy-weather/main/install | bash
curl -sSL https://raw.githubusercontent.com/apapamarkou/lazy-snapper/main/install | bash
curl -fsS https://dl.brave.com/install.sh | sh
sudo rpm --import -y https://packages.microsoft.com/keys/microsoft.asc &&
echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\nautorefresh=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/vscode.repo > /dev/null
sudo dnf update
sudo dnf install -y code
sudo dnf install -y https://download.cdn.viber.com/desktop/Linux/viber.rpm
sudo cat > /etc/yum.repos.d/AnyDesk-Fedora.repo << "EOF" 
[anydesk]
name=AnyDesk Fedora - stable
baseurl=http://rpm.anydesk.com/fedora/$basearch/
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://keys.anydesk.com/repos/RPM-GPG-KEY
EOF
dnf install -y anydesk

echo "✅ Done!"
